### ISSUE TITLE
Checkbox - Ripple radius is too big

### ISSUE THREAD

**Issue by Havret** [Havret/material-components-react#41]
Ripple radius for the checkbox is too big. 

Expected:

![image](https://user-images.githubusercontent.com/9103861/36640534-19c34d74-1a21-11e8-9791-1e69570186e0.png)

Actual:

![image](https://user-images.githubusercontent.com/9103861/36640537-2c59bbf8-1a21-11e8-9683-59cbbcd27dfe.png)

**Comment by Havret** [comment]
https://github.com/material-components/material-components-web/pull/2216

**Comment by englishextra** [comment]
![2018-03-12_231553](https://user-images.githubusercontent.com/537127/37328442-3669a680-26ab-11e8-94a4-98f709825415.png)

I have solved that via setTimeout. Though I understand the problem lies in `Element.getBoundingClientRect()` which has always been quite  tricky
```js
var rippleTimer;
var rippleHandler = function(){
	clearTimeout(rippleTimer);
	[].forEach.call(document.getElementsByClassName("mdc-button"), function(surface) {
		mdc.ripple.MDCRipple.attachTo(surface);
	});
	[].forEach.call(document.getElementsByClassName("mdc-icon-toggle"), function(iconToggle) {
		mdc.iconToggle.MDCIconToggle.attachTo(iconToggle);
	});
	[].forEach.call(document.getElementsByClassName("mdc-ripple-surface"), function(surface) {
		mdc.ripple.MDCRipple.attachTo(surface);
	});
	[].forEach.call(document.getElementsByClassName("mdc-card__primary-action"), function(el) {
		mdc.ripple.MDCRipple.attachTo(el);
	});
};
rippleTimer = setTimeout(rippleHandler, 400);
```
![37328509-82e8c234-26ab-11e8-8d01-e6f0492f645a](https://user-images.githubusercontent.com/537127/37328680-1fcc65ce-26ac-11e8-8a77-a0ec203444d4.jpg)
